version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 18
    commands:
      - echo "Installing AWS CDK CLI and dependencies..."
      - npm install -g aws-cdk
      - mvn clean install -DskipTests

  build:
    commands:
      - echo "Synthesizing CDK template..."
      - cdk synth > synth-output.txt 2>&1

      # Run compliance check (CDK-Nag)
      - echo "Running CDK-Nag compliance validation..."
      - grep -E "AwsSolutions-" synth-output.txt && echo "CDK-Nag violations found!" && exit 1 || echo " No CDK-Nag errors detected."

      # If above passes, proceed to deploy
      - echo "Deploying stack..."
      - cdk deploy AppStack --require-approval=never

