Resources:
  MyPipelineArtifactsBucket727923DD:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: PipelineStack/MyPipeline/ArtifactsBucket/Resource
  MyPipelineArtifactsBucketPolicyDFDA675B:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: MyPipelineArtifactsBucket727923DD
      PolicyDocument:
        Statement:
          - Action: s3:*
            Condition:
              Bool:
                aws:SecureTransport: "false"
            Effect: Deny
            Principal:
              AWS: "*"
            Resource:
              - Fn::GetAtt:
                  - MyPipelineArtifactsBucket727923DD
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - MyPipelineArtifactsBucket727923DD
                        - Arn
                    - /*
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: PipelineStack/MyPipeline/ArtifactsBucket/Policy/Resource
  MyPipelineRoleC0D47CA4:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: PipelineStack/MyPipeline/Role/Resource
  MyPipelineRoleDefaultPolicy34F09EFA:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:Abort*
              - s3:DeleteObject*
              - s3:GetBucket*
              - s3:GetObject*
              - s3:List*
              - s3:PutObject
              - s3:PutObjectLegalHold
              - s3:PutObjectRetention
              - s3:PutObjectTagging
              - s3:PutObjectVersionTagging
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - MyPipelineArtifactsBucket727923DD
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - MyPipelineArtifactsBucket727923DD
                        - Arn
                    - /*
          - Action: sts:AssumeRole
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - MyPipelineBuildDeployCDKBuildDeployCodePipelineActionRole3C228E49
                  - Arn
              - Fn::GetAtt:
                  - MyPipelineSourceGitHubSourceCodePipelineActionRoleB6D708AC
                  - Arn
        Version: "2012-10-17"
      PolicyName: MyPipelineRoleDefaultPolicy34F09EFA
      Roles:
        - Ref: MyPipelineRoleC0D47CA4
    Metadata:
      aws:cdk:path: PipelineStack/MyPipeline/Role/DefaultPolicy/Resource
  MyPipelineAED38ECF:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location:
          Ref: MyPipelineArtifactsBucket727923DD
        Type: S3
      Name: S3BucketPipeline
      PipelineType: V2
      RoleArn:
        Fn::GetAtt:
          - MyPipelineRoleC0D47CA4
          - Arn
      Stages:
        - Actions:
            - ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              Configuration:
                ConnectionArn: arn:aws:codeconnections:us-east-1:242332171291:connection/a9730499-9831-4922-a23e-79ab6c36cea2
                FullRepositoryId: NagarajanChelliya/app
                BranchName: master
              Name: GitHub_Source
              OutputArtifacts:
                - Name: SourceOutput
              RoleArn:
                Fn::GetAtt:
                  - MyPipelineSourceGitHubSourceCodePipelineActionRoleB6D708AC
                  - Arn
              RunOrder: 1
          Name: Source
        - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName:
                  Ref: CDKBuildProject96462ED9
              InputArtifacts:
                - Name: SourceOutput
              Name: CDK_Build_Deploy
              RoleArn:
                Fn::GetAtt:
                  - MyPipelineBuildDeployCDKBuildDeployCodePipelineActionRole3C228E49
                  - Arn
              RunOrder: 1
          Name: Build_Deploy
    DependsOn:
      - MyPipelineRoleDefaultPolicy34F09EFA
      - MyPipelineRoleC0D47CA4
    Metadata:
      aws:cdk:path: PipelineStack/MyPipeline/Resource
  MyPipelineSourceGitHubSourceCodePipelineActionRoleB6D708AC:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                Fn::GetAtt:
                  - MyPipelineRoleC0D47CA4
                  - Arn
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: PipelineStack/MyPipeline/Source/GitHub_Source/CodePipelineActionRole/Resource
  MyPipelineSourceGitHubSourceCodePipelineActionRoleDefaultPolicy5BACDF50:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: codestar-connections:UseConnection
            Effect: Allow
            Resource: arn:aws:codeconnections:us-east-1:242332171291:connection/a9730499-9831-4922-a23e-79ab6c36cea2
          - Action:
              - s3:Abort*
              - s3:DeleteObject*
              - s3:GetBucket*
              - s3:GetObject*
              - s3:List*
              - s3:PutObject
              - s3:PutObjectLegalHold
              - s3:PutObjectRetention
              - s3:PutObjectTagging
              - s3:PutObjectVersionTagging
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - MyPipelineArtifactsBucket727923DD
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - MyPipelineArtifactsBucket727923DD
                        - Arn
                    - /*
          - Action:
              - s3:PutObjectAcl
              - s3:PutObjectVersionAcl
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - MyPipelineArtifactsBucket727923DD
                      - Arn
                  - /*
        Version: "2012-10-17"
      PolicyName: MyPipelineSourceGitHubSourceCodePipelineActionRoleDefaultPolicy5BACDF50
      Roles:
        - Ref: MyPipelineSourceGitHubSourceCodePipelineActionRoleB6D708AC
    Metadata:
      aws:cdk:path: PipelineStack/MyPipeline/Source/GitHub_Source/CodePipelineActionRole/DefaultPolicy/Resource
  MyPipelineBuildDeployCDKBuildDeployCodePipelineActionRole3C228E49:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                Fn::GetAtt:
                  - MyPipelineRoleC0D47CA4
                  - Arn
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: PipelineStack/MyPipeline/Build_Deploy/CDK_Build_Deploy/CodePipelineActionRole/Resource
  MyPipelineBuildDeployCDKBuildDeployCodePipelineActionRoleDefaultPolicyF5D5A1EB:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
              - codebuild:StopBuild
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - CDKBuildProject96462ED9
                - Arn
        Version: "2012-10-17"
      PolicyName: MyPipelineBuildDeployCDKBuildDeployCodePipelineActionRoleDefaultPolicyF5D5A1EB
      Roles:
        - Ref: MyPipelineBuildDeployCDKBuildDeployCodePipelineActionRole3C228E49
    Metadata:
      aws:cdk:path: PipelineStack/MyPipeline/Build_Deploy/CDK_Build_Deploy/CodePipelineActionRole/DefaultPolicy/Resource
  CDKBuildProjectRoleC798FB78:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: PipelineStack/CDKBuildProject/Role/Resource
  CDKBuildProjectRoleDefaultPolicy977543DD:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: CDKBuildProject96462ED9
                    - :*
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: CDKBuildProject96462ED9
          - Action:
              - codebuild:BatchPutCodeCoverages
              - codebuild:BatchPutTestCases
              - codebuild:CreateReport
              - codebuild:CreateReportGroup
              - codebuild:UpdateReport
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":codebuild:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :report-group/
                  - Ref: CDKBuildProject96462ED9
                  - -*
          - Action:
              - s3:GetBucket*
              - s3:GetObject*
              - s3:List*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - MyPipelineArtifactsBucket727923DD
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - MyPipelineArtifactsBucket727923DD
                        - Arn
                    - /*
        Version: "2012-10-17"
      PolicyName: CDKBuildProjectRoleDefaultPolicy977543DD
      Roles:
        - Ref: CDKBuildProjectRoleC798FB78
    Metadata:
      aws:cdk:path: PipelineStack/CDKBuildProject/Role/DefaultPolicy/Resource
  CDKBuildProject96462ED9:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Cache:
        Type: NO_CACHE
      EncryptionKey: alias/aws/s3
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: false
        Type: LINUX_CONTAINER
      ServiceRole:
        Fn::GetAtt:
          - CDKBuildProjectRoleC798FB78
          - Arn
      Source:
        BuildSpec: |-
          {
            "phases": {
              "install": {
                "commands": [
                  "npm install -g aws-cdk",
                  "mvn clean install"
                ]
              },
              "build": {
                "commands": [
                  "cdk deploy AppStack --require-approval=never"
                ]
              }
            },
            "version": "0.2"
          }
        Type: CODEPIPELINE
    Metadata:
      aws:cdk:path: PipelineStack/CDKBuildProject/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/+1VTWvcMBD9LZlj0KrJllx8c9pS2jTBrHMzIcjjSaqsLBlJTliE/3uRZe9mG5qmH9AWCgZJ80Yzb5480pIvj0/40YF4cAts1gslax5KL3DNxIO7Dmga6mRHSmrioZhmVYDZeCFaggwOYWABRNOUXtwSZFUAF2c7+Or7DlfszY2ecwzMvebhtMc1+SpAPU623gxIo910Xhp9RpsnNsjg7Ly8Ps8v8vfv3o7QjbFIZfkJMm97YlArg+uir5XEHJGcm4JYas29UIVREmNgS15IDYld4sPSkFy25KYydm4JH5gULQ8ro6Juwrm+peZ0A1mAzkqNshMqRzS99hOD5BM35DgVE/UFa9QTvS9NMQeZGVdhEtt7gZ8/6KjmFoNDeAH4fNzn0Z8uMO6+tUL7fAs/4jQiac32ef4Yvf+i/E5R9n5J9ot1/nUnN/ZyZMqmVo8FzMkuzVeH8S3zeOd5akl7t5f2xeZ/Pe2f4Z+ek+kOjg9Z3UvV7F6xwpo7Ql+FgY1f8k/GYWArcqa3SHNzsV2TfRT34tXyhB/x44M7J+XC9trLlvgqjV8AO1Cz8lYHAAA=
    Metadata:
      aws:cdk:path: PipelineStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-3
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-3
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-4
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - il-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
      - Fn::Equals:
          - Ref: AWS::Region
          - us-west-2
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]

